apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: podinfo-secret
  namespace: default
spec:
  encryptedData:
    SECRET_KEY: AgC/zego5roHEam7XRo9uYB9kzyI4JIgz2TFlGyWmKs3O14+Ant4A2wswsqgiaCRPRG67Fk+5ycA1/Y6L/1hdN034LRiYLMSV6iT/xanqpNOIr1ixM4IPRBL0Fo5C8+1aPQHThDYLC/wPMFs5bFP2U8LhaWDByL4wY6zi0TY5K6t6HzLyD3i7pgPJeSio5Eq5mXNVZu2H+JVtY5+Wb1N8Q2CCaa6YRIgNbW4dRbkGW+yOzAO4Gvkp6mf74I16EzXBUKthPh3Ym41aecMf4d4UXLsFYQb9P/0UdERrGaHkYCOoXas1Jltn75LCmTKAR92Y6Z01GlXtxLsB2ChfxcpF0HuqhkKfRK/xKNX6orIM6NuWhu11MvwNOB14aOyF38y6kHPOBMRHNaC841YT+Tm5Oiw4YtLYhrkkbawKIsrk8Mj/NN34LvDoSrfghITQwIIXIqAOawBgFSV69q8TCN+tLxtV6AEPcQjHIgXPaNstZQHJKYvMdf/K0E7/j33wqZ74rnQH/q7OZUsraY3fWyt7UDRqtKXBP3Qx0L2OR+vrk+VKIp09f+DOwRtHvji2gndLc4Oz5k55zTlCtKbw1GDLe10coOQqc9117Uft2zmS9nNJRulV66IHMAJlJnDYyxdUDEDMJpA3c3FWA2kAugijD8lRHUncuEv4bszBAQtkfsy8hK09tjQ7ZDgjjlYsRbisiDETUAS1fLK7/9JQzWE/67Q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: podinfo-secret
      namespace: default

