apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: SECRET_KEY
  namespace: default
spec:
  encryptedData:
    password: AgB5xfo2UtukcEMB6+aI1ERRygOWNLzhW8qbtpxtCZ5Pp9ekMlEcHmy8lsnsu1Iz5D4sQS1wgP79cCbpJFe8rRPTCEUIwyih8Micq+XN13k2bVrZ34z/UATXRiAK6j5Tin50ztox/8uELySootldBllgCeFccpbKOXEoy+ACfbUalW/9aSGYP7IN8QV7XbkskwRyG29L3CYrqDzTDVtrCgElBr7vbzBi6+w5sQzu8dcu1T3FhL5oDiHrud8t0MRr4jUe8DiVT+1wLweR5hGDBSlEy9jUz/X96qkZN0VrzADZv24gee0jCH7lR6KQF4OWNiyy49xlY40EnmEK5e35IvV4I9NcaFqtkWOpS2iXIxLtslttbC9w9zdj6Xn1caOudG4TfE/oZNd1a+T7nMCKLn+ZMby7moA7iV9amwPX4dEa4+zstI6D3r/CaXwpkTLfuuSQ+tijHq3lnpBydOAWk2cilyX0Rk6HS5N0MVC25NfsTU+rVFGAAszwAswsvigs5e4u2n+b2NKFl3jvxZAw29n+uuNo0WeE7n+/EOr1D0lytJz4yEu3bbNM6zMoBaLBEHhmEneiHGWwJ0Rs1rTsWtF2oFeTjIKzZDZEUjjH8pnzA4jCvqgDAVe64LHVK+0KhOqyUjPw5p4/fI1PanC+sCaU8tJ2SteRnbEa6AMIXoIKB1Xk+mK4dw3/15TTtKIUnR3rU8W0e3eEofcnPwqf+9zb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: SECRET_KEY
      namespace: default
