apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-apps
resources:
- ./podinfo/namespace.yaml
- ./podinfo/deployment.yaml
- ./podinfo/service.yaml

images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 0.0.0 # {"$imagepolicy": "flux-system:podinfo"}